### PR TITLE
Add mailchimp.html example

### PR DESCRIPTION
**Pull request by leoj3n**
It took some work to make this a nice MailChimp template, so I thought I'd share it back, and suggest it be added as an example.

You can paste it into the template editor on MailChimp, and send yourself an email to see what it looks like.

Thanks for open sourcing Flybrid, hope you like this MailChimp template.

### CODE REVIEW

**Comment by leoj3n** [comment]
One not-so-obvious usage note that I'll point out:

To set the background of the "Haiku" area, you must upload an image to the MailChimp file manager, then copy the URL, then paste that in into the global template settings under the Haiku background section.

**Comment by ababic** [comment]
Hi @leoj3n.

I appreciate the time you've taken to put this together, and I like the idea of having more practical examples to get people started. But, I'm not really looking to extend the scope of this repo any further. 

If you wanted to add this template as a project to your own account, I'd be happy to link to it from the README. But, taking this template code on means maintaining it and supporting users who have any problems using it, and I'm not in position to do that, unfortunately.

**Comment by leoj3n** [comment]
Hey @ababic — If you open up the wiki I'll post it there.

**Comment by ababic** [comment]
He @leoj3n, whether it's in the wiki, or as a file, people will inevitably cut an paste the code and expect it to always work, and that's not something I'm in a position to support, sorry! Please let me know if you get your project set up, and I'll add a link to the README.

**Pull request closed without merging**
